name: flutter_web_dashboard
description: An app built using Flutter for web

environment:
  # You must be using Flutter >=1.5.0 or Dart >=2.3.0
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^0.2.0
  http: ^0.12.0+2
  intl: ^0.16.0
  json_annotation:

flutter:
 uses-material-design: true
 assets:
   - assets/images/
